#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

# Creator: Robert Buchberger
#          robert@buchberger.cc
#
# Creates a bitwarden session key and stores it for the wrapper script.
# This is a separate script because bw unlock --check is slow.
#
# Holy fuck shit jesus is pinentry a pain in the ass to use, who the hell
# designed this shit? Just let me ask for a fucking password and print the
# result to STDOUT, christ.
#
# Also, pinentry doesn't concern itself with such trivial matters as man
# pages. No no, you need to use the far shittier 'info' command, to get any
# actual documentation (which still sucks). This is written nowhere.

session_file="${XDG_CACHE_HOME:-$HOME/.cache}/bw_session.gpg"

# JESUS TITTYFUCKING CHRIST WHO THE FUCK ACCEPTS ARGUMENTS THIS WAY FUCK YOU
pinentry_result=$(
	pinentry <<-EOF
		SETTITLE Bitwarden CLI
		SETDESC Bitwarden CLI - Unlock Vault
		SETPROMPT Master Password: 
		GETPIN
	EOF
)

# First we have to fish the line we actually give a shit about from a bunch of
# extraneous pointless bullshit
pinentry_line=$(echo "$pinentry_result" | grep '^D')

# THEN we have to fucking strip the pointless fucking prefix becuase I guess
# without it we couldn't have accomplished the previous step, which WOULDN'T
# HAVE BEEN NECESSARY IN THE FIRST PLACE IF THIS FUKCING TOOL MADE ANY SENSE
master_pw=${pinentry_line#"D "}

[ "$master_pw" ] || exit 1

# And then we can actually fucking use the thing. Fuck this is why I hate the
# GNU coreutils. Everything is so much harder than it needs to be.
session_key=$(bw unlock --raw "$master_pw")

# If session key is populated, encrypt it to self and save.
([ ! "$session_key" = "" ] && echo "$session_key" |
	gpg --encrypt --default-recipient-self >"$session_file" &&
	echo "Session creation successful.") ||
	echo "Session creation failed. Troubleshooting required."
